CREATE DATABASE Movie_DB
GO
USE Movie_DB
GO
CREATE SCHEMA Movie
GO
CREATE TABLE Movie.Actors
(
	Act_ID INT PRIMARY KEY IDENTITY(1,1),
	Act_FName VARCHAR(20) NOT NULL,
	Act_LName VARCHAR(20) NOT NULL,
	Act_Gender VARCHAR(1) NOT NULL, 
)
GO
CREATE TABLE Movie.Directors
(
	Dir_ID INT PRIMARY KEY IDENTITY(1,1),
	Dir_FName VARCHAR(20) NOT NULL,
	Dir_LName VARCHAR(20) NOT NULL,
)
GO
CREATE TABLE Movie.Movies
(
	Mov_ID INT PRIMARY KEY IDENTITY(1,1),
	Mov_Title VARCHAR(50) NOT NULL,
	Mov_Year INT NOT NULL,
	Mov_Time INT NOT NULL,
	Mov_Lang VARCHAR(50) NOT NULL,
	Mov_DT_Rel DATETIME2 NOT NULL,
	Mov_Rel_Country VARCHAR(5) NOT NULL,
)
GO
CREATE TABLE Movie.Reviewer
(
	Rev_ID INT PRIMARY KEY IDENTITY(1,1),
	Rev_Name VARCHAR(30) NOT NULL,
)
GO
CREATE TABLE Movie.Genres
(
	Gen_ID INT PRIMARY KEY IDENTITY(1,1),
	Gen_Title VARCHAR(20) NOT NULL,
)
GO
CREATE TABLE Movie.Movie_Director
(
	Dir_ID INT NOT NULL,
	Mov_ID INT NOT NULL,
	PRIMARY KEY (Mov_ID, Dir_ID),
	FOREIGN KEY (Dir_ID) REFERENCES Movie.Directors(Dir_ID),
	FOREIGN KEY (Mov_ID) REFERENCES Movie.Movies(Mov_ID)
)
GO
CREATE TABLE Movie.Movie_Cast
(
	Act_ID INT NOT NULL,
	Mov_ID INT NOT NULL,
	Role VARCHAR(30) NOT NULL,
	PRIMARY KEY (Mov_ID, Act_ID),
	FOREIGN KEY (Act_ID) REFERENCES Movie.Actors(Act_ID),
	FOREIGN KEY (Mov_ID) REFERENCES Movie.Movies(Mov_ID)
)
GO
CREATE TABLE Movie.Movie_Genre
(
	Mov_ID INT NOT NULL,
	Gen_ID INT NOT NULL,
	PRIMARY KEY (Mov_ID, Gen_ID),
	FOREIGN KEY (Mov_ID) REFERENCES Movie.Movies(Mov_ID),
	FOREIGN KEY (Gen_ID) REFERENCES Movie.Genres(Gen_ID)
)
GO
CREATE TABLE Movie.Rating
(
	Mov_ID INT NOT NULL,
	Rev_ID INT NOT NULL,
	Rev_Stars INT NOT NULL,
	Num_of_Ratings INT NOT NULL,
	PRIMARY KEY (Mov_ID, Rev_ID),
	FOREIGN KEY (Mov_ID) REFERENCES Movie.Movies(Mov_ID),
	FOREIGN KEY (Rev_ID) REFERENCES Movie.Reviewer(Rev_ID)
)